# Quality Gates Configuration for CONSTRUCT
# Defines quality thresholds and checks for both CONSTRUCT development and user projects

construct_development:
  # Quality gates for CONSTRUCT's own shell/Python development
  scripts:
    max_script_length: 500  # lines
    required_error_handling: true
    required_documentation: true
    max_complexity: 10
    
  formatting:
    # Shell script formatting standards
    required_shebang: "#!/bin/bash"
    required_set_e: true
    required_color_definitions: true
    required_path_resolution: true  # Use SCRIPT_DIR pattern
    required_library_sourcing: true
    required_help_option: true
    max_function_length: 50  # lines
    
    # Variable naming conventions
    local_variables_lowercase: true
    global_variables_uppercase: true
    readonly_variables_uppercase: true
    
    # Function standards
    required_function_docs: true
    function_doc_format: "# Description\\n# Parameters:\\n#   $1 - param description\\n# Returns:\\n#   0 on success, 1 on failure"
    
    # Output formatting
    required_colored_output: true
    required_status_indicators: true  # ✅ ❌ ⚠️ 🔍 
    consistent_message_format: true
    
    # Error handling patterns
    required_parameter_validation: true
    required_exit_codes: true
    forbidden_silent_failures: true
    
    # Code organization
    max_nested_functions: 3
    required_main_function: true
    consistent_indentation: "  "  # 2 spaces
    max_line_length: 120
    
  documentation:
    required_readme_files: true
    required_inline_docs: true
    max_outdated_docs_days: 30
    
  testing:
    min_test_coverage: 70
    required_integration_tests: true
    
  structure:
    max_directory_depth: 4
    required_lib_functions: true
    max_code_duplication: 10  # percentage

user_projects:
  # Quality gates for Swift user projects
  swift_code:
    max_file_length: 300  # lines
    max_function_length: 50  # lines
    max_view_complexity: 20
    max_viewmodel_complexity: 30
    
  mvvm_compliance:
    max_mvvm_violations: 0
    max_hardcoded_values: 0
    min_design_token_usage: 10
    required_separation_of_concerns: true
    
  accessibility:
    required_dynamic_type: true
    required_accessibility_labels: true
    min_touch_target_size: 44  # points
    required_color_contrast: true
    
  performance:
    max_view_render_time: 16  # milliseconds (60fps)
    max_memory_usage_mb: 100
    required_lazy_loading: true
    
  swift6_compliance:
    required_main_actor: true
    required_async_await: true
    forbidden_completion_handlers: true
    required_sendable: true

checks:
  # Specific checks to run
  construct_checks:
    - script_syntax
    - error_handling
    - documentation_coverage
    - function_complexity
    - code_duplication
    - dependency_validation
    - script_formatting
    - variable_naming
    - function_documentation
    - output_formatting
    - path_resolution_patterns
    - library_sourcing_patterns
    
  swift_checks:
    - mvvm_violations
    - hardcoded_values
    - design_token_usage
    - accessibility_compliance
    - swift6_patterns
    - performance_patterns
    - file_organization
    - naming_conventions

thresholds:
  # Pass/fail thresholds
  critical_issues: 0      # Must be zero to pass
  major_issues: 0         # Must be zero to pass  
  minor_issues: 5         # Warning threshold
  warning_issues: 10      # Information threshold

reporting:
  # Report configuration
  output_format: "markdown"
  include_suggestions: true
  include_examples: true
  group_by_category: true
  show_file_locations: true
  
  categories:
    - "Critical"
    - "Architecture"
    - "Performance"
    - "Accessibility"
    - "Style"
    - "Documentation"

enforcement:
  # When to enforce quality gates
  on_commit: true
  on_push: true
  on_pr: true
  block_on_failure: true
  
  exemptions:
    # Files/patterns that can be exempted
    test_files: false      # Tests must also pass quality gates
    generated_files: true  # Generated files can be exempted
    legacy_files: false    # No legacy exemptions
    
auto_fix:
  # Rules that can be auto-fixed
  enabled: true
  safe_fixes_only: true
  
  fixable_issues:
    - "missing_spacing_tokens"
    - "hardcoded_colors"
    - "missing_accessibility_labels"
    - "outdated_syntax"
    
  confirmation_required:
    - "structural_changes"
    - "breaking_changes"
    - "logic_modifications"