#!/bin/bash

# Project Architecture Documentation Update Script
# Updates and maintains project architecture documentation based on active patterns

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Source library functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPTS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
source "$SCRIPTS_ROOT/../lib/common-patterns.sh"

# Accept PROJECT_DIR as parameter, default to current directory
PROJECT_DIR="${1:-.}"
PROJECT_DIR="$(cd "$PROJECT_DIR" && pwd)"

# Get patterns file
PATTERNS_FILE="$PROJECT_DIR/.construct/patterns.yaml"

echo -e "${BLUE}📚 Updating Project Architecture Documentation...${NC}"
echo "Project: $PROJECT_DIR"
echo ""

# Create docs directory if it doesn't exist
DOCS_DIR="$PROJECT_DIR/AI/docs/automated"
mkdir -p "$DOCS_DIR"
mkdir -p "$DOCS_DIR/_old"

# Function to get active patterns
get_active_patterns() {
    local patterns_file="$1"
    
    if [ ! -f "$patterns_file" ]; then
        echo -e "${YELLOW}⚠️ No .construct/patterns.yaml found${NC}" >&2
        echo -e "${YELLOW}Using default documentation generation${NC}" >&2
        return 1
    fi
    
    # Check for yq
    if ! command -v yq >/dev/null 2>&1; then
        echo -e "${RED}❌ Error: yq is required to read patterns.yaml${NC}" >&2
        echo -e "${YELLOW}Install yq: https://github.com/mikefarah/yq${NC}" >&2
        return 1
    fi
    
    # Extract active plugins
    yq eval '.plugins[]' "$patterns_file" 2>/dev/null || echo ""
}

# Generate base architecture overview
generate_base_architecture() {
    local output_file="$DOCS_DIR/architecture-overview-automated.md"
    
    echo -e "${YELLOW}Generating base architecture overview...${NC}"
    
    # Start with basic header
    cat > "$output_file" << EOF
# Project Architecture

**Last Updated**: $(date)
**Generated by**: update-architecture.sh
**Project**: $PROJECT_DIR

## Overview

This document provides an architectural overview of the project based on active patterns.

### Active Patterns
EOF

    # List active patterns
    if [ -f "$PATTERNS_FILE" ]; then
        local patterns=$(get_active_patterns "$PATTERNS_FILE")
        if [ -n "$patterns" ]; then
            echo "" >> "$output_file"
            echo "$patterns" | while read -r pattern; do
                echo "- $pattern" >> "$output_file"
            done
        else
            echo "- No patterns configured" >> "$output_file"
        fi
    else
        echo "- No patterns.yaml found" >> "$output_file"
    fi
    
    echo "" >> "$output_file"
    echo "---" >> "$output_file"
    echo "" >> "$output_file"
}

# Run pattern-specific architecture generators
run_pattern_generators() {
    local output_file="$DOCS_DIR/architecture-overview-automated.md"
    local patterns_run=0
    
    if [ ! -f "$PATTERNS_FILE" ]; then
        echo -e "${YELLOW}No patterns.yaml found, using generic documentation${NC}"
        return 0
    fi
    
    local patterns=$(get_active_patterns "$PATTERNS_FILE")
    if [ -z "$patterns" ]; then
        echo -e "${YELLOW}No active patterns found${NC}"
        return 0
    fi
    
    echo -e "${BLUE}Running pattern-specific generators...${NC}"
    
    while IFS= read -r pattern; do
        [ -z "$pattern" ] && continue
        
        # Look for pattern-specific architecture generator
        local generator="$SCRIPTS_ROOT/patterns/$pattern/generate-architecture.sh"
        
        if [ -f "$generator" ]; then
            echo -e "${GREEN}→ Running $pattern architecture generator${NC}"
            
            # Create temp file for pattern output
            local temp_file=$(mktemp)
            
            # Run the generator and capture output
            if bash "$generator" "$PROJECT_DIR" > "$temp_file" 2>&1; then
                # Append to main documentation
                echo "" >> "$output_file"
                echo "## $pattern Architecture" >> "$output_file"
                echo "" >> "$output_file"
                cat "$temp_file" >> "$output_file"
                ((patterns_run++))
            else
                echo -e "${YELLOW}⚠️ $pattern generator failed${NC}"
            fi
            
            rm -f "$temp_file"
        else
            echo -e "${YELLOW}→ No architecture generator for pattern: $pattern${NC}"
        fi
    done <<< "$patterns"
    
    return $patterns_run
}

# Generate pattern-specific documentation list
generate_pattern_documentation_list() {
    local output_file="$DOCS_DIR/architecture-overview-automated.md"
    
    # Check what pattern-specific docs exist
    local has_docs=false
    
    if [ -d "$PROJECT_DIR/AI/docs/patterns" ]; then
        local pattern_docs=$(find "$PROJECT_DIR/AI/docs/patterns" -name "*.md" -type f 2>/dev/null)
        if [ -n "$pattern_docs" ]; then
            echo "" >> "$output_file"
            echo "## Additional Documentation" >> "$output_file"
            echo "" >> "$output_file"
            echo "Pattern-specific documentation:" >> "$output_file"
            echo "$pattern_docs" | while read -r doc; do
                local doc_name=$(basename "$doc" .md)
                local relative_path=$(echo "$doc" | sed "s|$PROJECT_DIR/||")
                echo "- [$doc_name]($relative_path)" >> "$output_file"
            done
            has_docs=true
        fi
    fi
    
    if [ "$has_docs" = false ]; then
        echo "" >> "$output_file"
        echo "## Documentation" >> "$output_file"
        echo "" >> "$output_file"
        echo "No pattern-specific documentation found." >> "$output_file"
        echo "Pattern generators can create documentation in AI/docs/patterns/" >> "$output_file"
    fi
}

# Main execution
main() {
    echo "Updating project architecture documentation..."
    echo ""
    
    # Generate base architecture overview
    generate_base_architecture
    
    # Run pattern-specific generators
    run_pattern_generators
    local patterns_run=$?
    
    # If no pattern generators ran, add generic content
    if [ $patterns_run -eq 0 ]; then
        echo -e "${YELLOW}No pattern-specific architecture generators found${NC}"
        echo "" >> "$DOCS_DIR/architecture-overview-automated.md"
        echo "## Project Structure" >> "$DOCS_DIR/architecture-overview-automated.md"
        echo "" >> "$DOCS_DIR/architecture-overview-automated.md"
        echo "This project does not have pattern-specific architecture documentation." >> "$DOCS_DIR/architecture-overview-automated.md"
        echo "Add patterns to .construct/patterns.yaml to enable specialized documentation." >> "$DOCS_DIR/architecture-overview-automated.md"
    fi
    
    # Add documentation list
    generate_pattern_documentation_list
    
    # Add footer
    echo "" >> "$DOCS_DIR/architecture-overview-automated.md"
    echo "---" >> "$DOCS_DIR/architecture-overview-automated.md"
    echo "" >> "$DOCS_DIR/architecture-overview-automated.md"
    echo "*This document is auto-generated. To update, run: update-architecture.sh*" >> "$DOCS_DIR/architecture-overview-automated.md"
    
    echo ""
    echo -e "${BLUE}📚 Architecture Documentation Update Complete!${NC}"
    echo ""
    echo "Generated documentation:"
    echo "  - $DOCS_DIR/architecture-overview-automated.md"
    echo ""
    echo "Next steps:"
    echo "  update-context $PROJECT_DIR      # Update project context"
    echo "  check-quality $PROJECT_DIR       # Validate documentation quality"
}

# Show help if requested
if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    echo "Usage: $0 [PROJECT_DIR]"
    echo ""
    echo "Update project architecture documentation"
    echo ""
    echo "This script generates architecture documentation based on active patterns."
    echo "It reads patterns from PROJECT_DIR/.construct/patterns.yaml and runs"
    echo "pattern-specific architecture generators."
    echo ""
    echo "Arguments:"
    echo "  PROJECT_DIR   Project directory to document (default: current directory)"
    echo ""
    echo "Pattern generators should be located at:"
    echo "  patterns/[pattern-name]/generate-architecture.sh"
    echo ""
    echo "Examples:"
    echo "  $0                    # Document current directory"
    echo "  $0 .                  # Document current directory"
    echo "  $0 Projects/MyApp/ios # Document iOS project"
    exit 0
fi

# Run main function
main "$@"